[project]
name = "ali-datawhale-logic-inference"
version = "0.1.0"
description = "Add a short description here"
authors = ["Zend <zendwang040302@outlook.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = ">=3.12.4,<3.13"
pip = ">=24.0,<25"

[pypi-dependencies]
scipy = ">=1.14.0, <1.15"
openai = ">=1.37.0, <1.38"
tiktoken = ">=0.7.0, <0.8"
retry = ">=0.9.2, <0.10"
dashscope = ">=1.20.3, <1.21"
loguru = ">=0.7.2, <0.8"
ipykernel = ">=6.29.5, <6.30"
socksio = ">=1.0.0, <1.1"
langchain = ">=0.2.11, <0.3"
python-dotenv = ">=1.0.1, <1.1"
langchain-community = ">=0.2.10, <0.3"
transformers = ">=4.43.3, <4.44"
tqdm = ">=4.66.4, <4.67"
torch = ">=2.4.0, <2.5"
jupyter = ">=1.0.0, <1.1"
langchain-huggingface = ">=0.0.3, <0.1"
trl = ">=0.9.6, <0.10"
peft = ">=0.12.0, <0.13"
wandb = ">=0.17.5, <0.18"
loralib = ">=0.1.2, <0.2"
bitsandbytes = ">=0.42.0, <0.43"
